# Generated by Django 5.1.2 on 2025-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('service', models.CharField(choices=[('electrician', 'Electrician'), ('sweeper', 'Sweeper'), ('cleaner', 'Cleaner'), ('cook', 'Cook'), ('gardener', 'Gardener'), ('plumber', 'Plumber'), ('mechanic', 'Mechanic'), ('beautician', 'Beautician'), ('mistary', 'Mistary')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('phone_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField()),
                ('identity_proof', models.CharField(choices=[('adhaar-card', 'Adhaar Card'), ('pan-card', 'Pan Card'), ('votar-id-card', 'Votar ID Card')], max_length=20)),
                ('year_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('experience_certificate', models.FileField(upload_to='certificates/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
