# Generated by Django 5.1.2 on 2025-08-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_serviceprovider_password_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=900.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
