# Generated by Django 5.1.2 on 2025-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
